# use the latest ubuntu environment (18.04) available on travis
dist: bionic

language: go

env: GO111MODULE=on

go:
  - 1.13.x
  - master

# Only clone the most recent commit.
git:
  depth: 1

install: true

# Don't email me the results of the test runs.
notifications:
  email: false

script:
  - go test -v -race ./...  # Run all the tests with the race detector enabled
