# use the latest ubuntu environment (18.04) available on travis
dist: bionic

language: go

env: GO111MODULE=on

go:
  - 1.13.x

# Only clone the most recent commit.
git:
  depth: 1

install: true

# Don't email me the results of the test runs.
notifications:
  email: false

before_script:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $GOPATH/bin v1.23.1

script:
  - golangci-lint run       # run a bunch of code checkers/linters in parallel
  - go test -v -race ./...  # Run all the tests with the race detector enabled
